### ISSUE TITLE
pots: OSC2 opposite direction

### ISSUE THREAD

**Issue by mxa** [chairaudio/ILSE#11]

**Comment by mxa** [comment]
So just flip pins 1 and 3 of RV2 Osc2 detune @clwe ?

![grafik](https://user-images.githubusercontent.com/1220707/206916730-9314929e-35b9-4c73-8a88-eb1d2a362c4a.png)

**Comment by clwe** [comment]
Yes, a more negative voltage on the transistor increases the conductance and thus will tune the oscillator higher. I didn't think about this in the previous revisions.
